# Generated by Django 4.1.2 on 2022-10-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shakes',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
