# Generated by Django 4.1.2 on 2022-10-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0002_shakes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shakes',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
